//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICD.Profound.ConnectPRO.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICD.Profound.ConnectPRO.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Provider name=&quot;Profound&quot;&gt;
        ///	&lt;BaseUrl&gt;http://10.40.3.75/WebConferencing/&lt;/BaseUrl&gt;
        ///	&lt;Apps&gt;
        ///		&lt;App&gt;
        ///			&lt;Icon&gt;icon_videxio.png&lt;/Icon&gt;
        ///			&lt;Name&gt;Videxio VMR&lt;/Name&gt;
        ///			&lt;Steps&gt;
        ///				&lt;Step&gt;
        ///					&lt;Image&gt;Videxio_1.png&lt;/Image&gt;
        ///					&lt;Text&gt;First, open the Videxio Meeting Room in your web browser, then select the gear icon.&lt;/Text&gt;
        ///				&lt;/Step&gt;
        ///				&lt;Step&gt;
        ///					&lt;Image&gt;Videxio_2.png&lt;/Image&gt;
        ///					&lt;Text&gt;Change the Camera, Microphone, and Speakers to the correct devices.&lt;/Text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebConferencing {
            get {
                return ResourceManager.GetString("WebConferencing", resourceCulture);
            }
        }
    }
}
